CREATE TABLE IF NOT EXISTS tenant_settings (
    id                                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    timezone                          VARCHAR(100)    NOT NULL DEFAULT 'Asia/Tashkent',
    currency                          VARCHAR(10)     NOT NULL DEFAULT 'UZS',
    language                          VARCHAR(10)     NOT NULL DEFAULT 'ru',
    working_hours_start               TIME            DEFAULT '09:00:00',
    working_hours_end                 TIME            DEFAULT '21:00:00',
    working_days                      TEXT            DEFAULT '["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY"]',
    default_lesson_duration_min       INTEGER         DEFAULT 60,
    trial_lesson_duration_min         INTEGER         DEFAULT 45,
    max_group_size                    INTEGER         DEFAULT 20,
    auto_mark_attendance              BOOLEAN         DEFAULT FALSE,
    attendance_window_days            INTEGER         DEFAULT 7,
    sms_enabled                       BOOLEAN         DEFAULT FALSE,
    email_enabled                     BOOLEAN         DEFAULT TRUE,
    sms_sender_name                   VARCHAR(20),
    late_payment_reminder_days        INTEGER         DEFAULT 3,
    subscription_expiry_reminder_days INTEGER         DEFAULT 3,
    brand_color                       VARCHAR(50)     DEFAULT '#4CAF50',
    created_at                        TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at                        TIMESTAMPTZ,
    created_by                        VARCHAR(255),
    updated_by                        VARCHAR(255),
    version                           BIGINT          NOT NULL DEFAULT 0
);
